### ISSUE TITLE
Warnings while building on Android

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [jmcanterafonseca-iota/zebra-iota-edge-sdk#50]
- bwip-js

(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@zxing/browser/esm/readers/BrowserAztecCodeReader.js
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
...and 1 other occurrence
node_modules/@zxing/browser/esm/common/HTMLCanvasElementLuminanceSource.js
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
...and 1 other occurrence
node_modules/@zxing/browser/esm/readers/BrowserDatamatrixCodeReader.js
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
...and 1 other occurrence

...and 6 other files
(!) Import of non-existent export
src/components/Scanner.svelte
4:     import { createEventDispatcher, onMount } from 'svelte';
5:     import { BrowserMultiFormatReader as BMFR, BarcodeFormat, ChecksumException, DecodeHintType, Exception, FormatException, NotFoundException, Result } from '@zxing/library';
6:     import { BrowserMultiFormatReader, IScannerControls } from '@zxing/browser';
                                          ^
7:     import { __ANDROID__, __WEB__ } from '../lib/platforms';
8:     import { wait } from '../lib/helpers';
created public/build/bundle.js in 20.2s

**Comment by 7opf** [comment]
Fixed in https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/pull/43
