### ISSUE TITLE
Apply colors, backgrounds and icons suggested from UX

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [jmcanterafonseca-iota/zebra-iota-edge-sdk#69]

**Comment by 7opf** [comment]
I am working on this here: https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/pull/72

There are a lot of changes in the PR, but mostly deletions and moving of files.  I will need to rebase to get the recent PR changes.

In this PR I have packaged Janis' icons into a font and making the assets and public file structure more understandable.

One key thing missing from this PR will be Android splash screen which requires some more learning on my side to understand what I can delete from current Android files and how to ensure Splash Screen is only shown during app launch (no artificial delays).
