### ISSUE TITLE
Verifier App: When scanning invalid credential does not return to the Credentials screen

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [jmcanterafonseca-iota/zebra-iota-edge-sdk#87]
Scanner App --> Scan a Credential with the Camera --> Invalid Credential is shown --> Done is tapped --> You return to the scan screen with the Camera Off

Either it should be returned to the Scan with Camera on or to the Credential List

**Comment by 7opf** [comment]
Fixed in https://github.com/jmcanterafonseca-iota/zebra-iota-edge-sdk/pull/86
